#!/bin/sh
# Custom X500 with depth camera configuration

# Load standard x500
. ${R}etc/init.d-posix/airframes/4001_gz_x500

# Override parameters for simulation without GCS
param set-default COM_ARM_WO_GPS 1
param set-default NAV_DLL_ACT 0
param set-default COM_RCL_EXCEPT 4
param set-default NAV_RCL_ACT 0
param set-default COM_DL_LOSS_T 0
